apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-credentials
                key: mysql_root_password
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-credentials
                key: mysql_password          
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-claim
      volumes:
      - name: mysql-claim
        persistentVolumeClaim:
          claimName: mysql-claim
