apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-research
spec:
  selector:
    matchLabels:
      app: kubernetes-research
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-research
    spec:
      containers:
        - name: kubernetes-research
          image: spring-kubernetes-research
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: secret-credentials
                key: mysql_user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-credentials
                key: mysql_password
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: config
                key: datasource    