apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  ports:
    - name: http
      port: 8080
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway # relates to label in a pod description (under template block)
  ports:
    - name: http
      port: 8080
  type: ClusterIP


---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp # relates to label in a pod description (under template block)
  ports:
    - name: http
      port: 80
  type: LoadBalancer


---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
    - name: http
      port: 8161

    - name: endpoint
      port: 61616

  type: ClusterIP  