apiVersion: v1
kind: Pod
metadata:
  name: grafana-pod
  labels:
    app: grafana-pod
spec:
  containers:
    - image: "grafana/grafana-enterprise"
      name: grafana-pod
      ports:
        - containerPort: 3000