# Deployment----------
# spring-boot app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-research
spec:
  selector:
    matchLabels:
      app: kubernetes-research
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-research
    spec:
      containers:
        - name: kubernetes-research
          image: spring-kubernetes-research
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secret-credentials
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-credentials
                key: postgres_password
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: config
                key: datasource    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash","-c","sleep 20 && PGPASSWORD=$POSTGRES_PASSWORD psql $POSTGRES_DB -U $POSTGRES_USER -c \'CREATE SCHEMA IF NOT EXISTS test;\'"]
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-credentials
                key: postgres_password
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-claim
        # - mountPath: /pgconf
        #   name: init-script
      volumes:
      - name: postgres-claim
        persistentVolumeClaim:
          claimName: postgres-claim
      # - name: init-script
      #   configMap:
      #     name: postgres-init-configmap