# Deployment----------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-research
spec:
  selector:
    matchLabels:
      app: kubernetes-research
  replicas: 2
  template:
    metadata:
      labels:
        app: kubernetes-research
    spec:
      containers:
        - name: kubernetes-research
          image: spring-kubernetes-research
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: 8080
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://localohst:5432/new-test-db
          resources:
            requests:
              memory: 400Mi
              cpu: 200m

